@startuml
rectangle "autoware" {
  usecase "/awapi/awapi_awiv_adapter_node"
}

usecase "/autoware_state_machine"
usecase "/ad_sound_manager" #LightCoral
usecase "/sound_voice_alarm/audio_driver"
usecase "/sound_bgm/audio_driver"

(/awapi/awapi_awiv_adapter_node) --> (/ad_sound_manager) : /awapi/vehicle/get/status
(/autoware_state_machine) -> (/ad_sound_manager) : /autoware_state_machine/state
(/autoware_state_machine) <- (/ad_sound_manager) : /autoware_state_machine/state_sound_done
(/ad_sound_manager) -> (/sound_voice_alarm/audio_driver) : /sound_voice_alarm/audio_cmd
(/ad_sound_manager) <- (/sound_voice_alarm/audio_driver) : /sound_voice_alarm/audio_res
(/ad_sound_manager) --> (/sound_bgm/audio_driver) : /sound_bgm/audio_cmd
@enduml
