@startuml
left to right direction

rectangle "Autoware" {
  usecase "awapi_awiv_adapter_node\n/awapi/awapi_awiv_adapter_node" as awapi
}

usecase "autoware_state_machine" as state_machine
usecase "ad_sound_manager" as sound_manager #LightCoral
usecase "sound_voice_alarm/audio_driver" as voice_driver
usecase "sound_bgm/audio_driver" as bgm_driver

awapi --> sound_manager : /awapi/vehicle/get/status
state_machine --> sound_manager : /autoware_state_machine/state
sound_manager --> state_machine : /autoware_state_machine/state_sound_done
sound_manager --> voice_driver : /sound_voice_alarm/audio_cmd
voice_driver --> sound_manager : /sound_voice_alarm/audio_res
sound_manager --> bgm_driver : /sound_bgm/audio_cmd
@enduml
